profiles:
  none: []

  speech_only:
    - DOOR_OPEN
    - NAVIGATE_TO_INTERACTION_POINT
    - HUMAN_DETECTION
    - NAVIGATE_TO_ROOM
    - OBJECT_DETECTION
    - ESTIMATE_OBJECT_POSE
    - GRASP_OBJECT
    - NAVIGATE_TO_HUMAN
    - DELIVER_OBJECT
    - EXIT_ARENA

  detection_test:
    - DOOR_OPEN
    - NAVIGATE_TO_INTERACTION_POINT
    - HUMAN_DETECTION
    - LISTEN_COMMAND
    - NAVIGATE_TO_ROOM
    - ESTIMATE_OBJECT_POSE
    - GRASP_OBJECT
    - NAVIGATE_TO_HUMAN
    - DELIVER_OBJECT
    - EXIT_ARENA

  grasp_test:
    - DOOR_OPEN
    - NAVIGATE_TO_INTERACTION_POINT
    - HUMAN_DETECTION
    - LISTEN_COMMAND
    - NAVIGATE_TO_ROOM
    - OBJECT_DETECTION
    - NAVIGATE_TO_HUMAN
    - DELIVER_OBJECT
    - EXIT_ARENA

  no_navigation:
    - DOOR_OPEN
    - NAVIGATE_TO_INTERACTION_POINT
    - NAVIGATE_TO_ROOM
    - NAVIGATE_TO_HUMAN
    - EXIT_ARENA